### ISSUE TITLE
Adding Quit Key

### ISSUE THREAD

**Issue by sodface** [TAAPArthur/navboard#2]
Another question / request: what would be the best way to quit navboard in a touchscreen application? To me, having a quit key seems like the easiest solution but not many (any?) OSKs that I've tried include one.

I rebuilt navboard with the below patches and you can see the resulting quit key in the bottom right of the screenshot. It works well but using XK_0 seems wrong even though it doesn't appear to send the key before exiting.

```
--- ./functions.h.orig
+++ ./functions.h
@@ -24,5 +24,6 @@
 void setPressedFromCmd(KeyGroup*keyGroup, Key*key);
 
 void activateBoard(KeyGroup*keyGroup, Key*key);
+void exitNavboard(KeyGroup*keyGroup, Key*key);
 
 #endif

--- ./functions.c.orig
+++ ./functions.c
@@ -45,6 +45,10 @@
     activateBoardByName(key->arg.s ? key->arg.s: key->label);
 }
 
+void exitNavboard(KeyGroup*keyGroup, Key*key) {
+    exit(0);
+}
+
 void setKeyEnv(const Key* key) {
     char buffer[8];
     sprintf(buffer, "%d", key->value);

--- ./boards/qwerty.c.orig
+++ ./boards/qwerty.c
@@ -1,4 +1,5 @@
 #include "../navboard.h"
+#include "../functions.h"
 Key keys_qwerty[] = {
     {XK_grave},
     {XK_1},
@@ -63,6 +64,7 @@
     {XK_space, .weight = 5},
     {XK_Alt_R, .weight = 1},
     {XK_Control_R, .weight = 1},
+    {XK_0, .label="Quit", .onPress=exitNavboard},
 };
 
 REGISTER(qwerty, keys_qwerty);

```
![navboard_exit](https://user-images.githubusercontent.com/46695384/179338074-9d018033-b6b7-4ecc-95bf-905b5eba491e.png)

**Comment by TAAPArthur** [comment]
Take a look at the (new) README. I hope it will give some light how this can be done and if not I'm open to feed back.

So instead of modifying the boards, you can fully create your own after the program is installed. 

As for your patch, 
there's already a quit function in util.c I believe and you could just fully omit XK_0 if you don't want a key to be sent.

**Comment by sodface** [comment]
I've rebuilt against the latest source and everything looks good. All the board examples are awesome. Being able to (re)build new boards on the fly is a cool feature but I'm also okay with modifying the source and just building a new package.

Quit key with the function I missed the first time around is working great. Closing this issue.

```
--- ./boards/qwerty.c.orig
+++ ./boards/qwerty.c
@@ -1,4 +1,5 @@
 #include "../navboard.h"
+#include "../util.h"
 Key keys_qwerty[] = {
     {XK_grave},
     {XK_1},
@@ -63,6 +64,7 @@
     {XK_space, .weight = 5},
     {XK_Alt_R, .weight = 1},
     {XK_Control_R, .weight = 1},
+    {.label="Quit", .onPress=quit},
 };
```
