### ISSUE TITLE
Segmentation fault when font is not found

### ISSUE THREAD

**Issue by sodface** [TAAPArthur/navboard#3]
After the recent changes to the font search logic, a segmentation fault occurs if the font is not found:

```
sodco:~$ sudo mv /usr/share/fonts/liberation/LiberationMono-Regular.ttf .
sodco:~$ navboard qwerty
Segmentation fault
```

I was trying to test on my armv7 touchscreen device earlier and I couldn't figure out what was going on until I remembered I hadn't installed the fonts, which fixed it. Previously, a missing font resulted in a helpful warning and a graceful exit:

```
sodco:~$ navboard
Could not load font name /usr/share/fonts/TTF/LiberationMono-Regular.ttf
```

**Comment by TAAPArthur** [comment]
Thanks for catching that. The problem was in dtext_xcb and a fix has been pushed.

Going to just drop the dtext_xcb header in this repo to avoid some hassle

**Comment by sodface** [comment]
Tested and looks good to me. Thanks!
